Bring current documentation work back to dev branch (#120)
* Remove images/ directory

My suggested organization scheme is to move to the following eventual
directory structure at the root level of the repository:

  docs/
    docusaurus/
      [Whatever is needed by Docusaurus]
    internal/
      [One directory per theme]
  counterexamples/
  examples/
  schema/

In this scheme, the current buildings/, documentation_website/,
images/, and places/ directories are polluting the root. This commit
moves forward toward the suggested organization scheme by deleting
one of the pollutey directories, images/.

I'll look at further reorganization once Jennings' PR #97 is
merged.

* Document minimum required Node.js version for Docusaurus

The minimum required Node.js version is 15.0.0 because Docuaurus relies
on a JavaScript language feature called the nullish coalescing operator,
written `??=`. This feature is supported in Node.js 15.0.0 and higher:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

* Ignore files generated by Docusaurus build

* Fix incorrect title for Addresses schema documentation

* Correct GeoJson -> GeoJSON wherever it occurs...

* Build skeleton structure for Docusaurus docs (mega-commit)

This commit is doing a lot of work, sorry!

Some things involved:

1) Renamed the Docusaurus copy of the schema directory/ to docs/_schema/
   so Docusaurus will always ignore it and not crawl it for possible
   Documentation content.

2) Copied the examples/ directory to docs/_examples/ and created a
   prototype system to display validated schema example files as
   examples within the "Feature Types by Theme" documentation.

3) Reorganized the Documentation website around the following structure:

    - Concepts
        - Feature
        - Themes
            - ...
    - Feature Types by Theme
        - addresses
            - address
        - admins
            - adminBoundary
            - locality
        - buildings
            - footprint
        - places
            - place
        - transportation
            - connector
            - segment

4) Create a basic structure for the "Feature Type by Theme" pages,
   for example a little mini-table about their geometry types etc.

5) Sketched out some initial text for the "segment" and "connector"
   feature type documentation.

6) Broke the home page for the time being (it's a 404). Until we
   fix it you have to click "Documentation" to get to the nav tree.

7) Removed specific task force documentation files under a directory
   named task-force-docs/ to reduce pollution in the repository root.

Plus some other stuff I'm sure is good but I frankly can't remember.

* Set up the basic structure for documenting places/place

* Set up the basic structure for documenting buildings/footprint

* Set up basic structure for documenting admins theme features

* Set up basic structure for documenting addresses/address

* Add missing connectors in simple road example

* Restructure doc nav based on feedback from Ola, transportation team

* Improve and standardize additive sub-schema descriptions and titles

The reason for this change is that in the Docusaurus documentation,
the browsable version of the schema includes both the title (at the
top of the browsable control) and the description (at the bottom of
the control). The previous titles and descriptions were confusing
and failed to give much useful information.

* Improve title and description of root Overture schema

* building footprint examples

* tracing white house for example

* adding samples to footprint

* fixing yamlBasePath refs

* adding description to building class

* testing the description

* testing address schema

* fixing address

* putting address back to how it was

* adding comment into address

* adding white house ref

* Add example for access restriction and turn restriction tab for transportation documentation

* renaming footprint to building

* moved addresses into defs.yaml

* updating examples and schema files to pass validation

* adding schema ref and removing address

* moving themes / concepts around

* capitalization changes

* Simplify Docusaurus npm scripts and ignore build/ directory

* capitalization changes for consistency and additional concepts

* adding underscores to pages that are not ready yet

* mucking with plurality of theme names in the name of consistency

mucking with folder structures and ensuring consistency

* Throw errors on broken markdown links in the docs website

* Consolidate sidebar into sidebars.js, fix 404 on /, fix npm run build

* Re-hide unfinished transportation theme concept topics

Jennings had hidden these pending content using the underscore
technique and that got lost in my last refactor.

* Fix Docusaurus `npm run build` errors that slipped through

* Properly comment a paragraph of documentation

* Delete trailing </div>

* Really fix Docusaurus  - fourth time lucky

* Add places example

Also making themes plural

* adding json examples generated from YAML

* adjusting place schema

* adding content from confluence

* adding GERS

* adding better examples to admins

* Update GitHub actions to copy Docusaurus static site to staging bucket

* Try to fix GitHub action failure to get AWS credentials

Errors is:

    Error: Credentials could not be loaded, please check your action
    inputs: Could not load credentials from any providers

Fix attempted is:

    https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696

* Ensure obsolete files are deleted during docs website S3 sync

* Use S3 cheaper storage class for /latest/ docs website

Storage choices architecture for the staging bucket are as follows,
with rationale:

  1. Both the `latest/` prefix and the upcoming `pr/` prefix start
     in Intelligent Tiering since it has cheaper per-API-request
     options than any other tier.
  2. The `latest/` prefix stays in Intelligent Tiering (the bucket
     doesn't apply a lifecycle policy to it) because we anticipate
     folks will periodically want fairly rapid access to it.
  3. Each object under any `pr/<PR#/` prefix moves to Glacier Instant
     Retrieval after 20 days and is expired after 180 days using a
     lifecycle policy applied to the S3 bucket. This is because we
     anticipate the relevance of PR-specific documentation will
     decline rapidly toward zero and we don't want to waste money
     on it.

* Set the correct base URL when publishing Docusaurus website to S3

Otherwise the website errors out when you try to load it.

* Fix spelling error (very minor)

* Add GitHub action to PR-specific docs to staging on Pull Request

* Correct error in PR docs build GitHub action name

* Update index.mdx

small editorials

* Update index.mdx

added path to license. Can we include that content or do we duplicate the content?

* Update index.mdx

* Update index.mdx

* Added an example

* Shorten GitHub action names for usability

* Invalidate docs CDN cache after publishing new docs to staging bucket

I also updated the policy attached to the IAM role,
arn:aws:iam::207370808101:role/Overture_GitHub_schema-wg_Publish_Docs_Staging,
to give it the necessary permissions.

* Use dev branch for staging docs website /latest/

* Shorten GitHub action names for usability

* Invalidate docs CDN cache after publishing new docs to staging bucket

I also updated the policy attached to the IAM role,
arn:aws:iam::207370808101:role/Overture_GitHub_schema-wg_Publish_Docs_Staging,
to give it the necessary permissions.

* Update index.mdx

* Add sub-tabs for turn restrictions example, add lanes example

* Tidy and get tests passing again

* Improve turn restrictions example with collapsibles, better data

* Use code font for geometry types in feature summary table

---------

Co-authored-by: Jennings Anderson <jennings.anderson@gmail.com>
Co-authored-by: Sanjib Dutta <sdutta@microsoft.com>
Co-authored-by: Rob Soetewey <95700946+RobSoetewey-TomTom@users.noreply.github.com>
Co-authored-by: varapmsft <39808840+varapmsft@users.noreply.github.com>
Co-authored-by: jlockfb <124909460+jlockfb@users.noreply.github.com>